version: '2'
services:
  debug:
    image: phpstorm/php-71-apache-xdebug
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: jk=host.docker.internal

  mysql:
    image: phpstorm/mysql
    ports:
      - "33056:3306"
    volumes:
      - ./data:/var/lib/mysql