version: '2'
services:
  debug:
    image: phpstorm/php-71-apache-xdebug
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    links:
      - mysql

  mysql:
    image: mysql:latest
    command: ['--default-authentication-plugin=mysql_native_password']
    volumes:
      - db_vol:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: appDB
      MYSQL_ROOT_PASSWORD: 1234

volumes:
  db_vol: