version: '3'

services:
  db:
    container_name: db
    image: mysql:latest
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - db_vol:/var/lib/mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "9906:3306"  
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppassword"]
      timeout: 1s
      retries: 10

  php-apache:
    container_name: php-apache
    build: php-apache/
    volumes:
      - ./src:/var/www/html
      - ./conf/apache2/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./logs/apache2:/var/log/apache2
    depends_on:
      db:
        condition: service_healthy

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./src:/usr/share/nginx/html
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - 8000:80
    depends_on:
      - db
      - php-apache

volumes:
  db_vol:
